### PR TITLE
V 2.1.5 - Simulator, analysis and bug fixes. 

### PR DESCRIPTION
**Pull request by wroscoe**

### CODE REVIEW

**Comment by wroscoe** [comment]
I'm getting this error when upgrading my software on the PI

```
(env)pi@d2:~/donkeycar $ pip install -e .
Obtaining file:///home/pi/donkeycar
  Running setup.py (path:/home/pi/donkeycar/setup.py) egg_info for package from file:///home/pi/donkeycar
    extra_files ['templates/*', 'parts/controllers/templates/vehicle_list.html', 'parts/controllers/templates/session_list.html', 'parts/controllers/templates/base.html', 'parts/controllers/templates/vehicle.html', 'parts/controllers/templates/session.html', 'parts/controllers/templates/pilots_list.html', 'parts/controllers/templates/home.html', 'parts/controllers/templates/static/jquery-3.1.1.min.js', 'parts/controllers/templates/static/main.js', 'parts/controllers/templates/static/style.css', 'parts/controllers/templates/static/nipple.js', 'parts/controllers/templates/static/ui/1.12.1/jquery-ui.min.js', 'parts/controllers/templates/static/bootstrap/3.3.7/js/bootstrap.min.js', 'parts/controllers/templates/static/bootstrap/3.3.7/fonts/glyphicons-halflings-regular.woff', 'parts/controllers/templates/static/bootstrap/3.3.7/fonts/glyphicons-halflings-regular.ttf', 'parts/controllers/templates/static/bootstrap/3.3.7/fonts/glyphicons-halflings-regular.woff2', 'parts/controllers/templates/static/bootstrap/3.3.7/css/bootstrap.min.css']
    
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python3/dist-packages (from donkeycar==2.1.5)
Requirement already satisfied (use --upgrade to upgrade): pillow in /usr/lib/python3/dist-packages (from donkeycar==2.1.5)
Requirement already satisfied (use --upgrade to upgrade): docopt in /home/pi/env/lib/python3.4/site-packages (from donkeycar==2.1.5)
Requirement already satisfied (use --upgrade to upgrade): tornado in /home/pi/env/lib/python3.4/site-packages (from donkeycar==2.1.5)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python3/dist-packages (from donkeycar==2.1.5)
Requirement already satisfied (use --upgrade to upgrade): keras in /home/pi/env/lib/python3.4/site-packages (from donkeycar==2.1.5)
Requirement already satisfied (use --upgrade to upgrade): h5py in /usr/lib/python3/dist-packages (from donkeycar==2.1.5)
Downloading/unpacking python-socketio (from donkeycar==2.1.5)
  Downloading python-socketio-1.8.1.tar.gz
  Running setup.py (path:/tmp/pip-build-1x51vx0u/python-socketio/setup.py) egg_info for package python-socketio
    
    warning: no files found matching 'README.md'
Requirement already satisfied (use --upgrade to upgrade): flask in /usr/lib/python3/dist-packages (from donkeycar==2.1.5)
Downloading/unpacking eventlet (from donkeycar==2.1.5)
  Downloading eventlet-0.21.0-py2.py3-none-any.whl (403kB): 403kB downloaded
Downloading/unpacking opencv-python (from donkeycar==2.1.5)
  Could not find any downloads that satisfy the requirement opencv-python (from donkeycar==2.1.5)
Cleaning up...
No distributions at all found for opencv-python (from donkeycar==2.1.5)
Storing debug log for failure in /home/pi/.pip/pip.log

```

**Comment by wroscoe** [comment]
@tawnkramer It looks like [this](https://github.com/wroscoe/donkey/blob/4d69e6fbdc91e9c2e7a8fcc1f81172560733aed9/donkeycar/parts/stores/tub.py#L369) is the only place opencv is used and it doesn't even look like it's imported. Can you switch this to use PIL. Here's [an example.](https://stackoverflow.com/questions/12201577/how-can-i-convert-an-rgb-image-into-grayscale-in-python)

**Comment by tawnkramer** [comment]
https://github.com/wroscoe/donkey/blob/dev/donkeycar/parts/stores/tub.py

line 355 has the import cv2.

but I'm happy to change that to PIL, or better yet, numpy.

**Comment by wroscoe** [comment]
For now we can just remove the install reference to opencv until we have a Rpi disk image with it installed. If someone want's to use the stacked version they can figure out how to install opencv but it won't prevent regular installs for this release.

**Comment by tawnkramer** [comment]
Sounds good. That should be fixed now. The main code pulling in opencv was
in parts/__init__.py from .cv.cv import ImgStack

That's commented out now. Will be nice to have OpenCV installed in the
image so we can start using it. Thanks.

Went ahead and changed cv2 usage in tub.py to use numpy.

**Pull request merged**
