### PR TITLE
Replace Keras library with TensorFlow API

### PR DESCRIPTION
**Pull request by joekickass**
Recent versions of TensorFlow has adopted the Keras API. Replacing
the Keras library with the TensorFlow Keras implementation lessens
the risk of library mismatch and makes upgrading TensorFlow easier.

Also trim whitespace from changed files.

### CODE REVIEW

**Comment by joekickass** [comment]
I've only run unit test on the patch, no validation on the car yet. Should probably test both training a new model and running it, as well as running an old model trained before applying the patch.

**Comment by wroscoe** [comment]
Thanks for this! I'll look to merge into the dev branch.

**Comment by wroscoe** [comment]
make your second pr against dev

- Will

**Comment by joekickass** [comment]
will do

**Pull request closed without merging**
